### ISSUE TITLE
Dispatcher filters: Unable to use regular expressions in path/protocol/query/url

### ISSUE THREAD

**Issue by henrykuijpers** [bstopp/puppet-aem#100]
As defined in the documentation: https://helpx.adobe.com/experience-manager/dispatcher/using/dispatcher-configuration.html#ExamplefilterUsingRegularExpressions
Regular expressions can be used if the value is between single quotes instead of double quotes. However, in the erb-template the values are always encapsulated in double quotes.

**Comment by bdhoine** [comment]
Could we come to a consensus here to get this feature in the module? It would really simplify the config.

**Comment by bstopp** [comment]
I am preparing to release a dedicated Dispatcher module here:

https://github.com/adobe/puppet-dispatcher

I will be deprecating support for the Dispatcher in this module and will not enhance it any further.

The Adobe Puppet Dispatcher module supports both regex and globs OOTB, in a much more efficient manner.
