### ISSUE TITLE
FR: Add support for secure renders

### ISSUE THREAD

**Issue by Jarodiv** [bstopp/puppet-aem#116]
For our current project secure communication between the Dispatcher and AEM is required. Currently that Dispatcher feature is not supported by this module.

See:
https://helpx.adobe.com/experience-manager/dispatcher/using/dispatcher-configuration.html#DefiningPageRenderersrenders

**Comment by dploeger** [comment]
Created a PR for that. Be sure, to use the correct, SSL-enabled package, though.

Additionally, on an Ubuntu-16.04 I had to add two links to `libcrypto.so.10 => libcrypto.so.1.0.0` and `libssl.so.10 => libssl.so.1.0.0` in `/lib/x86_64-linux-gnu` for it to work. But that maybe an OS/AEM compilation issue.

**Comment by Jarodiv** [comment]
Thanks for spending time on this. There already is PR #117 that adds the same changes plus the corresponding tests and default values :)

**Comment by dploeger** [comment]
Oh, allright. Didn't catch that.

**Comment by dploeger** [comment]
@bstopp Can #117  be merged?

**Comment by Jarodiv** [comment]
@dploeger if you need that PR, as we did, we created a temporary fork in our companies account, that includes this PR (on master) and one for #124 on develop (not promoted to master yet).
-> https://github.com/Netcentric/puppet-aem

That way @bstopp can take all the time he needs to validate and perform these merges.

**Comment by dploeger** [comment]
@Jarodiv Yes, we're using our branch from the PR currently, but using official version is always better. Especially as something like the metadata.json of Puppet modules doesn't understand git references.

**Comment by Jarodiv** [comment]
100% agree on that
