### ISSUE TITLE
Module does not allow invalidate and invalidateHandler to be used at the same time

### ISSUE THREAD

**Issue by jasper-s** [bstopp/puppet-aem#118]
We've started using both invalidate and invalidateHandler dispatcher directives in combination and they seem work fine. Can you specify the reason why this is not allowed in the module?

**Comment by bdhoine** [comment]
@bstopp this issue can be closed, a commit to use both was merged to the master branch

**Comment by bstopp** [comment]
I merged a change that supported this at some point... but i'll be damned if i can't figure out which PR it was. Thank's @bdhoine for the changes!
