### ISSUE TITLE
Puppet re-run may take ages on hosts with a grown AEM instance

### ISSUE THREAD

**Issue by Jarodiv** [bstopp/puppet-aem#124]
During its run the AEM module searches the installation folder for a already present crx-quickstart jar.

When being re-running on hosts with a grown AEM instance the `crx-quickstart/repository` folder can become quite huge, causing the `find` call that is used for the search to take ages.

Corresponding output from Puppet debug:
> Debug: Executing '/bin/find /opt/aem-publish -name "cq-quickstart-\*-standalone\*.jar" -type f'

One solution would be to simply exclude the `crx-quickstart/repository` folder from the search. After all its more than unlikely to find the quickstart jar there.

**Comment by bstopp** [comment]
Fixed in 2.6.1
