### ISSUE TITLE
Replace the search for the quickstart jar with static lookups

### ISSUE THREAD

**Issue by Jarodiv** [bstopp/puppet-aem#126]
Currently during each run of this module a search for the crx-quickstart jar is performed. Depending on the host and the filetree within the AEM installation folder this search may take very and possibly block the whole puppet run (e.g. as described in #124).

In his comment to a PR in a fork of this project @cwoeltge pointed out that there are only two possible locations for the quickstart jar and the search for it could be replaced by a simple lookup for static paths (https://github.com/Netcentric/puppet-aem/pull/3#pullrequestreview-148470154).

Is there any need for searching the jar? If not I would suggest to replace it as suggested by Conrad.

**Comment by bstopp** [comment]
Fixed in 2.6.1
