### ISSUE TITLE
issue with deserialization firewall missing item

### ISSUE THREAD

**Issue by tevolo** [bstopp/puppet-aem#136]
this generates an invalid list” 
    'osgi_configs':
      'DeserializationFirewall':
        'pid': com.adobe.cq.deserfw.impl.DeserializationFirewallImpl
        'properties':
          'firewall.deserialization.whitelist':
            - 'sun.util.calendar.'
            - 'com.adobe.'
            - 'com.day.'
            - 'com.google.api.client.auth.oauth2.'
            - 'com.scene7.'
            - 'java.'
            - 'javax.'
            - 'oracle.sql.'
            - 'org.apache.http.auth'
            - 'org.apache.http.impl.auth'
            - 'org.apache.jackrabbit.'
            - 'org.apache.sling.'

**Comment by bdhoine** [comment]
add more info when logging issues like what is the expected result, what is the faulty result and put code in a snippet so it is formatted and reads smoothly

**Comment by bstopp** [comment]
Turns out this was a bug on the configuration side - not something as a failure of the tool.
