### ISSUE TITLE
Hotfix support

### ISSUE THREAD

**Issue by rveede** [bstopp/puppet-aem#38]
It would be nice if this module could also support the installation of hotfixes/packages during startup/installation by putting copying the hotfix zip files into the /crx-quickstart/install folder.

The list of files to copy into that folder could be provided in the aem::instance { 'aem' : } declaration.

What do you think?

**Comment by bstopp** [comment]
I am all for this! Currently I'm working on supporting OSGi configurations as part of the pre-initialization process (putting the properties file in the *./install* folder. I will look into this next.

However instead of providing the files as a list, i am thinking a custom defines/resource type, that way you can manage where the files come from. For example sourcing the file, you can supply:

* *file()* type resource
* *packageshare* keyword which requires Adobe ID Username/Password to lookup and d/l the file

Thoughts?

**Comment by ronaldvaneede** [comment]
That sounds good to me. How is your progress on this?

Maybe the issue name should be changed to something like 'pre-initialization instal support'?

**Comment by bstopp** [comment]
I'm wrapping up two other features. I think i'll have this done in the next week or two. I'm going to add it to the next release feature set though.

**Comment by zipkid** [comment]
Hi,

We need this functionality.
Do you have any code done for this?
Maybe a base we can build onto...?

**Comment by bstopp** [comment]
No work has been done on this yet.

**Comment by zipkid** [comment]
I suppose i can start coding on this using the existing types/providers as examples and using rest endpoint /crx/packmgr/service.jsp, /crx/packmgr/service/.json and /crx/packmgr/service/console.html

**Comment by bstopp** [comment]
This will come out with 3.0, but i do not have a project timeline on that at the moment.

**Comment by zipkid** [comment]
Your comment suggests you have something near completion...
Should i just wait for that?
If you have nothing yet, do you object to accepting PR's?

**Comment by bstopp** [comment]
I'll accept PRs, but the design for 3.0 will differ significantly from the current implementation; so it may not mesh with the planned changes. Hate for there to be wasted work. 

Re: near completion? No, unfortunately not.

**Comment by zipkid** [comment]
In wat way 'different'? 
If you let me know, my work may not be 'wasted'.

**Comment by bstopp** [comment]
I'm adding support for this for 2.4; the architectural changes for 3.0 will start to take effect with this feature. Those changes are to extract API calls from the providers into gems. To that end i have started the work on those gems. The one for this feature is [here](https://github.com/bstopp/crx-packmgr-api-client-gem).
