### ISSUE TITLE
Replication Agent management support

### ISSUE THREAD

**Issue by ronaldvaneede** [bstopp/puppet-aem#47]
Hi @bstopp are you perhaps already working on something to manage replication agents?
If not then that is something I would like to contribute to this module.

**Comment by bstopp** [comment]
I have not started on something like that. However rather than be specific, i'd like to do a custom type that can create/delete arbitrary resources/properties on an instance. then create helper types (like replication agents) to call it.

Thoughts?

**Comment by ronaldvaneede** [comment]
My idea was to create a type that would do a request to /bin/wcmcommand to call the createPage command to create the replication agent and then have a type to do a request to that page's /jcr:content in order to configure the agent.
You could then also re-use those types to do create other pages and configure them.

**Comment by bstopp** [comment]
Closed via #51
