### ISSUE TITLE
Runmodes not set correctly?

### ISSUE THREAD

**Issue by crivabene** [bstopp/puppet-aem#50]
Deploying an instance through the module sets the runmodes only to the one specifed by the type attribute, missing the standard ones as it happens with a traditional installation. This does not seem to cause troubles but I am not sure if it is supported (can't find reference in the docs).

Instance deployed with puppet-aem:
`java -Xmx1024m -server -Djava.awt.headless=true -Dsling.run.modes=author -jar crx-quickstart/app/cq-quickstart-6.2.0-standalone-quickstart.jar start -c crx-quickstart -i launchpad -p 4502 -Dsling.properties=conf/sling.properties`

Instance deployed traditionally (unpack):
`java -server -Xmx1024m -XX:MaxPermSize=256M -Djava.awt.headless=true -Dsling.run.modes=author,crx3,crx3tar -jar crx-quickstart/app/cq-quickstart-6.2.0-standalone-quickstart.jar start -c crx-quickstart -i launchpad -p 4502 -Dsling.properties=conf/sling.properties`

**Comment by stewbv** [comment]
We used this to deploy our 6.2 instances:
Author instance:
java -Xmx4096m -server -Djava.awt.headless=true -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=30303 -Dsling.run.modes=author,dev,nosamplecontent -jar crx-quickstart/app/cq-quickstart-6.2.0-standalone-quickstart.jar start -c crx-quickstart -i launchpad -p 4502 -Dsling.properties=conf/sling.properties

/system/console/status-slingsettings 
Give me:
Apache Sling Settings

Sling ID = f5a85f03-27a4-4b4f-9336-88426aa0ea50
Sling Name = Instance f5a85f03-27a4-4b4f-9336-88426aa0ea50
Sling Description = Instance with id f5a85f03-27a4-4b4f-9336-88426aa0ea50 and run modes [dev, crx3, nosamplecontent, author, crx3tar]
Sling Home = /opt/aem/author/crx-quickstart
Sling Home URL = file:/opt/aem/author/crx-quickstart/
Run Modes = [dev, crx3, nosamplecontent, author, crx3tar]

crx3 and crx3tar are the default for 6.2

**Comment by crivabene** [comment]
@stewbv, thanks for the feedback. I'll close this then!
