### ISSUE TITLE
Extend dispatcher-farm to support new elements (enhancement)

### ISSUE THREAD

**Issue by 3xil3** [bstopp/puppet-aem#53]
Extend dispatcher farm support for new elements (/path, /selectors, /extension, /suffix). See [docs](https://docs.adobe.com/docs/en/dispatcher/disp-config.html#par_title_1996763852)

```
/006 {
        /type "deny"
        /path "/content"
        /selectors '(feed|rss|pages|languages|blueprint|infinity|tidy)'
        /extension '(json|xml|html)'
}
```

**Comment by bstopp** [comment]
Closed via #55
