### ISSUE TITLE
Unrecognized option during Jar unpack

### ISSUE THREAD

**Issue by thedonkdonk** [bstopp/puppet-aem#60]
Notice: /Stage[main]/Main/Aem::Instance[instance.example.com-author]/Aem::Package[instance.example.com-author]/Exec[instance.example.com-author unpack]/returns: 25.07.2016 12:14:00.799 *ERROR* [main] -b: Unrecognized option (use -h for more information)
    Notice: /Stage[main]/Main/Aem::Instance[instance.example.com-author]/Aem::Package[instance.example.com-author]/Exec[instance.example.com-author unpack]/returns: 25.07.2016 12:14:00.800 *ERROR* [main] -u: Unrecognized option (use -h for more information)
    Error: java -jar /opt/aem-quickstart.jar -b /opt/aem/author -unpack returned 1 instead of one of [0]
    Error: /Stage[main]/Main/Aem::Instance[instance.example.com-author]/Aem::Package[instance.example.com-author]/Exec[instance.example.com-author unpack]/returns: change from notrun to 0 failed: java -jar /opt/aem-quickstart.jar -b /opt/aem/author -unpack returned 1 instead of one of [0]

Using

    [root@dlmhaem02 ~]# java -version
    java version "1.8.0_101"
    Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
    [root@dlmhaem02 ~]# lsb_release -a
    LSB Version:    :core-4.1-amd64:core-4.1-noarch
    Distributor ID: CentOS
    Description:    CentOS Linux release 7.2.1511 (Core)
    Release:        7.2.1511
    Codename:       Core
    [root@dlmhaem02 ~]# uname -a
    Linux dlmhaem02 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Let me know if I can provide any other information.

**Comment by bstopp** [comment]
Version of the AEM Jar File?

**Comment by noatec** [comment]
6.1

**Comment by bstopp** [comment]
You have a bad Jar file; I've got 10 6.1 VM's working no prob...

**Comment by bstopp** [comment]
Non-repeatable issue. Source jar probably culprit.

**Comment by thedonkdonk** [comment]
Confirmed.
