### ISSUE TITLE
Failed initial puppet run using example

### ISSUE THREAD

**Issue by sambanks** [bstopp/puppet-aem#64]
Hi There

I am trying to use your module on a clean install of puppet with a simple manifest and am getting the following:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at '.'; expected '}' at /etc/puppet/modules/aem/manifests/config.pp:65 on node

My details are:

Red Hat Enterprise Linux Server release 6.5 
puppet-server-3.8.7-1.el6.noarch

Cheers
Sam

**Comment by bstopp** [comment]
Please check the compatibility. This module only works on Puppet v4.0 or higher; or Puppet 3.8 with the _future_ parser enabled.

Thank you.

**Comment by sambanks** [comment]
Whoops sorry about that. Thanks for the prompt response!
