### ISSUE TITLE
aem:dispatcher rhel7 

### ISSUE THREAD

**Issue by michaeldiender-shinesolutions** [bstopp/puppet-aem#73]
As mentioned in the limitations, there are issues with the dependency between the aem:dispatcher and the puppet apache module. 

can you confirm that this would be causing the following:

Error: Systemd start for httpd failed!
journalctl log for httpd:
-- Logs begin at Thu 2016-12-08 09:15:15 AEDT, end at Thu 2016-12-08 10:41:44 AEDT. --
Dec 08 10:40:55 ip-172-31-7-203.ap-southeast-2.compute.internal systemd[1]: Stopping The Apache HTTP Server...
Dec 08 10:40:56 ip-172-31-7-203.ap-southeast-2.compute.internal systemd[1]: Stopped The Apache HTTP Server.
Dec 08 10:41:44 ip-172-31-7-203.ap-southeast-2.compute.internal systemd[1]: Starting The Apache HTTP Server...
Dec 08 10:41:44 ip-172-31-7-203.ap-southeast-2.compute.internal httpd[12057]: httpd: Syntax error on line 38 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.modules.d/dispatcher.load: Cannot load modules/mod_dispatcher.so into server: /etc/httpd/modules/mod_dispatcher.so: failed to map segment from shared object: Permission denied

Do you know of a work around? other than not using the aem:dispatcher class?

**Comment by bstopp** [comment]
No this seems more like the owner of the `mod_dispatcher.so` has a higher privilege than the user running Apache itself. I don't suppose you have an example manifest or yaml file? Or can you confirm if you're changing the defaults for the apache user/group attributes? Are you running SELinux on that RHEL system? 

I feel like you may have stumbled on a bug.

**Comment by michaeldiender-shinesolutions** [comment]
I haven’t changed the user/group of the apache. Defaults to root. When I apply the puppet manifest a second time it is successful - it is only when applying the manifest the first time it fails. (Would the selinux disallow it the first time, but allow it the second time?)



dispatcher::installation_source: 'https://www.adobeaemcloud.com/content/companies/public/adobe/dispatcher/dispatcher/_jcr_content/top/download_8/file.res/dispatcher-apache2.4-linux-x86-64-4.2.1.tar.gz'
dispatcher::filename: 'dispatcher-apache2.4-linux-x86-64-4.2.1.tar.gz'
dispatcher::tmp_dir: '/tmp/dispatcher-apache2.4-linux-x86-64-4.2.1'
dispatcher::module_filename: 'dispatcher-apache2.4-4.2.1.so'
dispatcher::aws_user: 'ec2-user'
dispatcher::aws_group: 'ec2-user’

Yes, it is SE enabled.

SELinux status:                 enabled


I do see that the .so file has lesser permissions than the other so file (-rwxr-xr-x)

-rw-r--r--. 1 root root 684242 Dec  8 12:23 dispatcher-apache2.4-4.2.1.so
lrwxrwxrwx. 1 root root     48 Dec  8 12:23 mod_dispatcher.so -> /etc/httpd/modules/dispatcher-apache2.4-4.2.1.so

**Comment by bstopp** [comment]
What are the permissions on the dispatcher's so file after installation? And if you're able to, can you tell me the umask for the _root_ user on the target system?

**Comment by michaeldiender-shinesolutions** [comment]
-rw-r--r--. 1 root root 684242 Dec  8 12:23 dispatcher-apache2.4-4.2.1.so
lrwxrwxrwx. 1 root root     48 Dec  8 12:23 mod_dispatcher.so -> /etc/httpd/modules/dispatcher-apache2.4-4.2.1.so

umask for the root user is 0022

**Comment by bstopp** [comment]
Can you try this branch in your Puppet file and let me know if you still have the same issue on the _first run_? Thanks!

https://github.com/bstopp/puppet-aem/tree/bug/disp-mod-perms

**Comment by michaeldiender-shinesolutions** [comment]
the permissions on the dispatcher-apache2.4-4.2.1.so where adjusted. 
-rwxr-xr-x. 1 root root 684242 Dec  8 13:32 dispatcher-apache2.4-4.2.1.so

but same error:

Syntax error on line 38 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.modules.d/dispatcher.load: Cannot load modules/mod_dispatcher.so into server: /etc/httpd/modules/mod_dispatcher.so: failed to map segment from shared object: Permission denied

debug logs:

[debug.log.txt](https://github.com/bstopp/puppet-aem/files/638292/debug.log.txt)

**Comment by bstopp** [comment]
OK, it must be some nuance of the RHEL OS itself. Let me dig into it and see what I can find.

**Comment by michaeldiender-shinesolutions** [comment]
After disabling se, the dispatcher was applied successfully.  Thanks for you help.

**Comment by bstopp** [comment]
This is for me to look into ensuring support for SE Linux being enabled. Thank you for narrowing it down!

**Comment by henrykuijpers** [comment]
I actually just had this issue and solved it by adding in my conf:
``
  # apply SELinux type 'httpd_modules_t' to /etc/httpd/modules
  exec { 'update-modules-SELinux-type':
    command => "/bin/chcon -Rv -t httpd_modules_t /etc/httpd/modules/ && /sbin/semanage fcontext -a -t httpd_modules_t \"/etc/httpd/modules(/.*)?\"",
    user    => 'root',
    require  => File['/etc/httpd/modules/mod_dispatcher.so']
  }
``

There was already something in the scripts to set the correct seltype, but this was invoked too early (before the mod_dispatcher.so & the original dispatcher so file were created in the modules directory).

Would love to see a better approach in this.

**Comment by henrykuijpers** [comment]
You can actually verify this by going to /etc/httpd/modules and performing 'ls -Z', then you see that all modules are httpd_modules_t, but the dispatcher so files are httpd_config_t.

**Comment by henrykuijpers** [comment]
I'm using the 'jhcook/centos7' box v3.10.0.514.21.2 btw, which seems to be CentOS 7.2

**Comment by henrykuijpers** [comment]
Just created a pull request that should fix this issue: https://github.com/bstopp/puppet-aem/pull/87

**Comment by henrykuijpers** [comment]
Maybe a better fix for this issue is to not fix it in this AEM module, but instead use https://forge.puppet.com/puppet/selinux ? If you require your mod_dispatcher.so to be created in order to apply the selinux context, then you should be there, right? 

What do you think @bstopp?

**Comment by bstopp** [comment]
I'm not sure. I looked over the docs and it doesn't appear that there is anything in that module other than managing the state of SELinux as a whole. Though I'm not familiar with the configuration rules of the SELinux to know what resources in there can be used to manage the state for non-standard modules.

**Comment by killakam3084** [comment]
> I actually just had this issue and solved it by adding in my conf:
> 
> ```
>   # apply SELinux type 'httpd_modules_t' to /etc/httpd/modules
>   exec { 'update-modules-SELinux-type':
>     command => "/bin/chcon -Rv -t httpd_modules_t /etc/httpd/modules/ && /sbin/semanage fcontext -a -t httpd_modules_t \"/etc/httpd/modules(/.*)?\"",
>     user    => 'root',
>     require  => File['/etc/httpd/modules/mod_dispatcher.so']
>   }
> ```
> 
> There was already something in the scripts to set the correct seltype, but this was invoked too early (before the mod_dispatcher.so & the original dispatcher so file were created in the modules directory).
> 
> Would love to see a better approach in this.

That y'all so much for this thread. Probably saved me days of debugging! Good ol AEM always there to throw you for a loop.

**Comment by bdhoine** [comment]
The solution you propose is not for this module and also not really a good one. First remark is that it will run on every puppet apply. The context is applied on the resource itself. By looking at your exec you are setting context to the httpd modules directory and also the modules that are in there so this is more related to the apache module.

You also state that the SELinux config is applied too soon but when using this on a RHEL7 with SELinux enabled I don't see any problems?

**Comment by bstopp** [comment]
I would suggest looking at the [Adobe Puppet Dispatcher](https://github.com/adobe/puppet-dispatcher) module. I've effectively deprecated all dispatcher support in this module in favor of that implementation. 

If you run into these issues using that module, if you open a ticket, I'll post a patch. However, I haven't run into these issues since that was released.
